[package]
edition = "2021"
name = "spawn-examples"
version = "0.1.0"

[dependencies]
env_logger = "0.10.0"
log = {version = "0.4.8", features = ["std"]}
prost = "0.12.1"
prost-types = "0.12.1"
rocket = "=0.5.0-rc.3"
spawn-rs = {path = "../spawn-rs"}

[build-dependencies]
tonic-build = "0.8"
