[package]
edition = "2021"
name = "spawn-examples"
version = "0.1.0"

[dependencies]
env_logger = "0.10.0"
prost-types = "0.11"
spawn-rs = {path = "../spawn-rs"}
tokio = {version = "1.25.0", features = ["full"]}
