name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
